name: Build

on: [push, pull_request]


jobs:
  build:
    name: Windows-Build
    runs-on: windows-latest

    steps:
      - name: Clone CloudCompare
        uses: actions/checkout@v2
        with:
          repository: 'CloudCompare/CloudCompare'
          ref: '67d2beb5eb18a826efad55b4d863fb905a2353bb'
          submodules: true

      - name: Clone PythonPlugin
        uses: actions/checkout@v2
        with:
          path: 'plugins/private/CloudCompare-PythonPlugin'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v1
        with:
          activate-environment: CloudCompareDev
          auto-activate-base: false
          python-version: "3.7"
          miniconda-version: 'latest'

      - name: Install Dependencies
        run: |
          conda install -c conda-forge qt=5.12.* pybind11
          pip install numpy

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cmake  `
            -B build `
            -DCMAKE_INSTALL_PREFIX=install `
            -DPLUGIN_PYTHON=ON `
            .

      - name: Build
        run: cmake --build build --parallel --config Release
#
#
      - name: Install
        run: cmake --install build

      - name: Run Tests
        run: |
          pip install pytest
          cd plugins/private/CloudCompare-PythonPlugin
          pytest --cloudcompare_exe ${{ github.workspace }}/install/CloudCompare/CloudCompare.exe tests