name: Build

on: [ push, pull_request ]


jobs:
  Windows-Build:
    name: Windows
    runs-on: windows-latest

    steps:
      - name: Clone CloudCompare
        uses: actions/checkout@v2
        with:
          repository: 'CloudCompare/CloudCompare'
          ref: 'ad12a8f8441cf01ec8c7abdffb0b5acceda570ac'
          submodules: true

      - name: Clone PythonPlugin
        uses: actions/checkout@v2
        with:
          path: 'plugins/private/CloudCompare-PythonPlugin'

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: CloudCompareDev
          auto-activate-base: false
          python-version: "3.7"
          miniconda-version: 'latest'

      - name: Install Dependencies
        run: |
          conda install -c conda-forge qt=5.12.* pybind11 ninja
          pip install numpy

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cmake  `
            -G Ninja `
            -B build `
            -DCMAKE_INSTALL_PREFIX=install `
            -DPLUGIN_PYTHON=ON `
            .

      - name: Build
        run: cmake --build build --parallel --config Release

      - name: Install
        run: cmake --install build

      - name: Run Tests
        run: |
          pip install pytest
          cd plugins/private/CloudCompare-PythonPlugin
          pytest --cloudcompare_exe ${{ github.workspace }}/install/CloudCompare/CloudCompare.exe tests


  Ubuntu-Build:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update -qq
          sudo apt install build-essential cmake ninja-build libqt5svg5-dev libqt5opengl5-dev qt5-default qttools5-dev qttools5-dev-tools pybind11-dev xvfb
          python3 -m pip install pytest numpy

      - name: Clone CloudCompare
        uses: actions/checkout@v2
        with:
          repository: 'CloudCompare/CloudCompare'
          ref: 'ad12a8f8441cf01ec8c7abdffb0b5acceda570ac'
          submodules: true

      - name: Clone PythonPlugin
        uses: actions/checkout@v2
        with:
          path: 'plugins/private/CloudCompare-PythonPlugin'

      - name: Configure CMake
        shell: pwsh
        run: |
          mkdir build
          cmake  `
            -G Ninja `
            -B build `
            -DPLUGIN_PYTHON=ON `
            -DCMAKE_BUILD_TYPE=Release `
            .

      - name: Build
        run: cmake --build build --parallel

      - name: Install
        run: sudo cmake --install build

      - name: Run Tests
        run: |
          cd plugins/private/CloudCompare-PythonPlugin
          export LD_LIBRARY_PATH=/usr/local/lib
          xvfb-run python3 -m pytest --cloudcompare_exe /usr/local/bin/CloudCompare tests